# Generated by Django 5.0.8 on 2025-09-03 22:38

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COTA', 'Cota condominial'), ('EXTRA', 'Extra/Rateio'), ('DESPESA', 'Despesa')], default='COTA', max_length=12)),
                ('competencia', models.DateField(help_text='Mês/ano de referência')),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('boleto_pdf', models.FileField(blank=True, help_text='Anexe o boleto/2ª via ou documento de cobrança (opcional).', null=True, upload_to=portal.models.boleto_upload_path)),
                ('comprovante_pdf', models.FileField(blank=True, help_text='Comprovante enviado pelo morador.', null=True, upload_to=portal.models.comprovante_upload_path)),
                ('comprovante_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Selecione se a cobrança for para vários moradores.', related_name='lancamentos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('morador_alvo', models.ForeignKey(blank=True, help_text='Use para endereçar esta cobrança a um morador específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_diretos', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, help_text='Se marcado, o morador atual da unidade verá este lançamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='condominios.unidade')),
            ],
            options={
                'ordering': ['-vencimento', '-criado_em'],
            },
        ),
    ]
