services:
  db:
    image: postgres:15-alpine
    container_name: n8n-postgres
    restart: always
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: "Speakers1*"
      TZ: America/Fortaleza
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5678:5678"
    environment:
      # Login da UI (Basic Auth)
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: "Speakers1*"

      # Chave de criptografia de credenciais
      N8N_ENCRYPTION_KEY: "b544ad8e59a0a286278d0e4f850e9f67235f1f612e6851b1aa0f2529bbb7aabf"

      # Banco de dados do n8n
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: db
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: "Speakers1*"

      # Instância (local)
      N8N_HOST: "0.0.0.0"
      N8N_PORT: 5678
      N8N_PROTOCOL: "http"
      N8N_EDITOR_BASE_URL: "http://localhost:5678"
      WEBHOOK_URL: "http://localhost:5678"
      GENERIC_TIMEZONE: "America/Fortaleza"
      TZ: "America/Fortaleza"

      # Permissões do arquivo de config
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"

      # Telemetria (opcional)
      DIAGNOSTICS_ENABLED: "false"
      N8N_DIAGNOSTICS_ENABLED: "false"

      # Execuções (boa prática)
      EXECUTIONS_MODE: "regular"
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: "none"
      EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: "168"  # horas (7 dias)

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pg_data:
  n8n_data: