# Generated by Django 5.0.8 on 2025-08-30 03:46

import assembleias.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembleia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('quando', models.DateTimeField(help_text='Data e hora da assembleia')),
                ('convocacao_pdf', models.FileField(blank=True, help_text='Edital/Convocação (PDF)', null=True, upload_to=assembleias.models.ata_convocacao_path)),
                ('ata_pdf', models.FileField(blank=True, help_text='Ata final da reunião (PDF)', null=True, upload_to=assembleias.models.ata_final_path)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(help_text='Condomínio ao qual a assembleia pertence', on_delete=django.db.models.deletion.CASCADE, related_name='assembleias', to='condominios.condominio')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembleias_criadas', to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Se vazio, todos os moradores do condomínio verão.', related_name='assembleias_destinadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quando', '-criado_em'],
            },
        ),
    ]
