# Generated by Django 5.0.8 on 2025-08-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COTA', 'Cota condominial'), ('EXTRA', 'Extra/Rateio'), ('DESPESA', 'Despesa')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês de referência (ex.: 2025-08-01)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='condominios.unidade')),
            ],
            options={
                'ordering': ['-vencimento'],
            },
        ),
    ]
