# Generated by Django 5.0.8 on 2025-08-29 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-vencimento', '-criado_em']},
        ),
        migrations.AddField(
            model_name='lancamento',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, help_text='Selecione se a cobrança for para vários moradores.', related_name='lancamentos_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='morador_alvo',
            field=models.ForeignKey(blank=True, help_text='Use para endereçar esta cobrança a um morador específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_diretos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='competencia',
            field=models.DateField(help_text='Mês/ano de referência'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.CharField(choices=[('COTA', 'Cota condominial'), ('EXTRA', 'Extra/Rateio'), ('DESPESA', 'Despesa')], default='COTA', max_length=12),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Se marcado, o morador atual da unidade verá este lançamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='condominios.unidade'),
        ),
    ]
