# Generated by Django 5.0.8 on 2025-08-30 13:43

import django.db.models.deletion
import financeiro.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('financeiro', '0002_alter_lancamento_options_lancamento_destinatarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='boleto_pdf',
            field=models.FileField(blank=True, help_text='Anexe o boleto/2ª via ou documento de cobrança (opcional).', null=True, upload_to=financeiro.models.boleto_upload_path),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='comprovante_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='comprovante_pdf',
            field=models.FileField(blank=True, help_text='Comprovante enviado pelo morador.', null=True, upload_to=financeiro.models.comprovante_upload_path),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, help_text='Selecione se a cobrança for para vários moradores.', related_name='fin_lancamentos_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='morador_alvo',
            field=models.ForeignKey(blank=True, help_text='Use para endereçar esta cobrança a um morador específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_lancamentos_diretos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Se marcado, o morador atual da unidade verá este lançamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_lancamentos', to='condominios.unidade'),
        ),
    ]
