# Generated by Django 5.0.8 on 2025-08-29 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='condominios.condominio')),
            ],
            options={
                'unique_together': {('condominio', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('bloco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='condominios.bloco')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominios.condominio')),
                ('morador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('condominio', 'bloco', 'numero')},
            },
        ),
    ]
