# Generated by Django 5.0.8 on 2025-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='permite_compartilhar',
            field=models.BooleanField(default=False),
        ),
    ]
